apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: heartbeat
spec:
  type: heartbeat
  version: 8.4.2
  elasticsearchRef:
    name: elasticsearch
  config:
    heartbeat.monitors:
    - type: tcp
      id: elastic-internal-route
      name: Elastic Internal Route
      schedule: '@every 5s'
      hosts: ["elasticsearch-es-http.default.svc:9200"]
    - type: tcp
      id: kibana-internal-route
      name: Kibana Internal Route
      schedule: '@every 5s'
      hosts: ["kibana-kb-http.default.svc:5601"]
    - type: http
      id: argocd-service
      name: Draco ArgoCD
      hosts: ["https://argocd.draco.scalar.cloud:443"]
      schedule: '@every 5s'
  deployment:
    replicas: 1
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0
