---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundryvtt-data-pv-claim
  namespace: foundryvtt
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40G