---
apiVersion: v1
kind: Service
metadata:
  name: foundryvtt-web
  labels:
    name: foundryvtt-web
  namespace: foundryvtt
spec:
  selector:
    app: foundryvtt
  ports:
    - name: web
      port: 80
      targetPort: 4444