namespace: metallb-system

resources:
  - github.com/metallb/metallb//manifests?ref=v0.11.0

configMapGenerator:
  - name: config
    files:
      - config/configmap.yaml

generatorOptions:
  disableNameSuffixHash: true