apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: redis-statestore
  namespace: default
spec:
  version: 6.0.6
  storageType: Durable
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
