apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: wikijs-postgres
  namespace: wikijs
spec:
  version: "10.6"
  storage:
    storageClassName: "longhorn"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
  terminationPolicy: DoNotTerminate
