apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: wikijs-postgres
  namespace: wikijs
spec:
  version: "13.2"
  storageType: Durable
  storage:
    storageClassName: "longhorn"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: DoNotTerminate
