apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: wikijs-postgres
  namespace: wikijs
spec:
  version: "9.6-v1"
  replicas: 2
  storage:
    storageClassName: "longhorn"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  archiver:
    storage:
      storageSecretName: s3-secret
      s3:
        bucket: kubedb-wikijs-backups
