apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fleet-server
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - fleet-server.draco.scalar.cloud
      secretName: fleet-server-draco-tls
  rules:
    - host: fleet-server.draco.scalar.cloud
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: fleet-server-agent-http
                port:
                  number: 8220
