apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ha-code
  namespace: home-assistant
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'You a netrunner?'
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - ha-code.draco.scalar.cloud
      secretName: ha-code-draco-tls
  rules:
    - host: ha-code.draco.scalar.cloud
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: home-assistant-codeserver
                port:
                  number: 12321
