apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: socks-shop
  namespace: socks-shop
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
    - hosts:
        - socks.draco.scalar.cloud
      secretName: socks-draco-tls
  rules:
    - host: socks.draco.scalar.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-end
                port:
                  number: 80
