apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: statping
  namespace: statping
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
    - hosts:
        - status.draco.scalar.cloud
      secretName: status-draco-tls
  rules:
    - host: status.draco.scalar.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: statping
                port:
                  number: 10099
