apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wikijs
  namespace: wikijs
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  tls:
    - hosts:
        - wiki.lab.scalar.cloud
      secretName: wikijs-tls
  rules:
    - host: wiki.lab.scalar.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: draco-wikijs
                port:
                  name: http